create table urls (
  id                            bigint generated by default as identity not null,
  name                          varchar(255),
  created_at                    timestamptz not null,
  constraint pk_url primary key (id)
);

create table urlChecks (
  id                            bigint generated by default as identity not null,
  statusCode                    bigint,
  title                         varchar(MAX),
  h1                            varchar(MAX),
  description                   varchar(MAX),
  urlId                         bigint REFERENCES urls(id),
  created_at                    timestampz not null,
  primary key (id)
);