DROP TABLE IF EXISTS urls;

create table urls (
  id                            bigint generated by default as identity not null,
  name                          varchar(255),
  created_at                    timestamp not null,
  primary key (id)
);

DROP TABLE IF EXISTS url_checks;

create table url_checks (
  id                            bigint generated by default as identity not null,
  status_code                   bigint,
  title                         varchar(255),
  h1                            varchar(255),
  description                   text,
  url_id                        bigint,
  created_at                    timestamp not null,
  primary key (id)
);
