DROP TABLE IF EXISTS urls;

create table urls (
  id                            bigint generated by default as identity not null,
  name                          varchar(255),
  created_at                    timestamp not null,
  primary key (id)
);

DROP TABLE IF EXISTS urlChecks;

create table urlChecks (
  id                            bigint generated by default as identity not null,
  statusCode                    bigint,
  title                         varchar(255),
  h1                            varchar(255),
  description                   text,
  urlId                         bigint,
  created_at                    timestamp not null,
  primary key (id)
);
