DROP TABLE IF EXISTS urls CASCADE;


create table urls (
  id                            bigint generated by default as identity not null,
  name                          varchar(255),
  created_at                    timestamp not null,
  primary key (id)
);

DROP TABLE IF EXISTS urlChecks CASCADE;

create table urlChecks (
  id                            bigint generated by default as identity not null,
  statusCode                    bigint,
  title                         text,
  h1                            text,
  description                   text,
  urlId                         bigint REFERENCES urls(id),
  created_at                    timestamp not null,
  primary key (id)
);
